### PR TITLE
btax endpoint

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
Work in progress, to be coordinated with changes in B-Tax, such as [https://github.com/open-source-economics/B-Tax/pull/38](https://github.com/open-source-economics/B-Tax/pull/38) and [https://github.com/open-source-economics/B-Tax/pull/40](https://github.com/open-source-economics/B-Tax/pull/40)

### CODE REVIEW

**Comment by talumbau** [comment]
hmmm... I don't think this would go here. Any btax calls should happen in https://github.com/OpenSourcePolicyCenter/deploy, at least as far as I can tell. Can you help me understand the reasoning here?

**Comment by PeterDSteinberg** [comment]
@talumbau I was thinking we would need for B-Tax a function equivalent to [this run_nth_year function](https://github.com/PeterDSteinberg/drop-q/blob/9816fb80e1f8348e2ce1a50fedf49e2f7cc4befb/dropq/dropq.py#L271) because we will have different column names and a different way of differencing versus baseline.  I thought that B-Tax would not be broken up by number of years.

**Comment by talumbau** [comment]
OK I see. You can either add that in the celery task portion here:
https://github.com/OpenSourcePolicyCenter/deploy/blob/master/celery_tasks.py

or in B-Tax itself. `drop-q` is pretty specific to Tax-Calculator at this point. Since there is no disclosure avoidance issue with B-Tax right now, I think it would make sense to not tie the two packages together.

**Comment by PeterDSteinberg** [comment]
I see @talumbau .  I can move as much of the B-Tax functionality as possible out of here.   I'm working on @jdebacker 's PR in B-Tax now and can add it as PR to one of his branches.

**Comment by talumbau** [comment]
The functions for packaging up the answer in some nice way can either be on the celery-side, flask-side, or done by the package that does the actual calculation. You could argue we should move the post-processing in `dropq` to the celery task. I'm fine with that, but it just happened that the post-processing went inside `dropq` itself.

**Comment by PeterDSteinberg** [comment]
Closing this.  Changes will be made in B-Tax and deploy

**Pull request closed without merging**
