### PR TITLE
Use Behavior.has_response() to insulate dropq.py from Behavior internals

### PR DESCRIPTION
**Pull request by martinholmer**
This pull request insulates the dropq.py logic from internal changes in the Tax-Calculator Behavior class.

@MattHJensen @feenberg @talumbau

### CODE REVIEW

**Comment by martinholmer** [comment]
@talumbau,  Do you have any objections to drop-q pull request #3?  If not, do you want to merge it into the master branch?  I don't have permission to do that.

@MattHJensen

**Comment by talumbau** [comment]
Ah, right I forgot about this. No objection. I looked at `has_response` and it looks good. Thanks!

**Comment by feenberg** [comment]
On Fri, 8 Jul 2016, Martin Holmer wrote:

> 
> @talumbau, Do you have any objections to drop-q pull request #3? If not, do
> you want to merge it into the master branch? I don't have permission to do
> that.
> 
> @MattHJensen

If this isn't done, what is the effect of behavior on dropq?

I don't exactly understand what the pull is doing, but shouldn't the 
selection of records to drop depend upon behavior? I recall that dropped 
records should be selected from among those contributing to net tax 
liability to be effective in disturbing the data. If an extreme behavioral 
coefficient causes taxpayers to have zero liability, would that disrupt 
the dropq selection?

We might mitigate this by limiting the behavioral effect or by checking 
for post-behavior tax liability.

Perhaps someone will reply outlining the current logic for dropq.

dan

**Comment by martinholmer** [comment]
Dan @feenberg asked:
> If this [pull request #3] isn't done, what is the effect of behavior on dropq?
>
> I don't exactly understand what the pull is doing, but shouldn't the selection of records to drop depend upon behavior? I recall that dropped records should be selected from among those contributing to net tax liability to be effective in disturbing the data. If an extreme behavioral coefficient causes taxpayers to have zero liability, would that disrupt the dropq selection?

Dan,  pull request #3 has no effect on dropq logic.  Whatever the dropq algorithm is doing with respect to Behavior logic now (after the merger of #3) is exactly the same as it was doing before the merger of pull request #3.  I've never been involved in dropq work, so I have no idea what the answers to your questions are.  Maybe those who have been involved in the development of dropq code can answer your questions.

@MattHJensen @talumbau

**Pull request merged**
